language: generic
sudo: required
#dist: trusty

branches:
  only:
  - master
  - travis-ci

env:
- PLATFORM="-j4 MACHINE=kvm_x86_64"

before_install:
- cd build-config
- sudo apt-get update
- sudo apt-get install build-essential
- sudo apt-get install -y stgit u-boot-tools util-linux gperf device-tree-compiler python-all-dev xorriso autoconf automake bison flex texinfo libtool realpath gawk libncurses5 libncurses5-dev bc dosfstools mtools pkg-config git wget help2man libexpat1 libexpat1-dev fakeroot python-sphinx rst2pdf

install: true

script:
- make $PLATFORM download
- make $PLATFORM crosstool-ng
- travis_wait 50 make $PLATFORM xtools
- make $PLATFORM uclibc
- travis_wait 50 make $PLATFORM kernel
- travis_wait 50 make $PLATFORM all
